name: Advanced Spell Check
on: [push, pull_request]

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for Typos
        uses: streetsidesoftware/cspell-action@v6
        with:
          # Проверяем всё, используя конфиг cspell.json
          config: 'cspell.json'
          # Если хотите проверять ТОЛЬКО измененные файлы (быстрее):
          # incremental_files_only: true
