name: "Spellcheck"
on: [push, pull_request]

jobs:
  run-spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: "CSpell Check"
        uses: streetsidesoftware/cspell-action@v6
        with:
          # Файлы, которые нужно проверить (весь репозиторий)
          files: "**"
          # Чтобы билд не падал сразу, а показал все ошибки
          incremental_files_only: false
          # Путь к конфигу (создайте его в корне)
          config: "cspell.json"
